ASUSFETest/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CAP_Student_Group_Count__c</fullName>
        <description>A count of the total Student Group records where Status is True and PeopleSoft Code is CP00, CP01, or CP02. Used to determine if this Contact should be flagged as a College Achievement Plan participant.</description>
        <inlineHelpText>A count of the total Student Group records where Status is True and PeopleSoft Code is CP00, CP01, or CP02. Used to determine if this Contact should be flagged as a College Achievement Plan participant.</inlineHelpText>
        <label>CAP Student Group Count</label>
        <summaryFilterItems>
            <field>Student_Group__c.SG_Status__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Student_Group__c.SG_PeopleSoft_Code__c</field>
            <operation>equals</operation>
            <value>CP00, CP01, CP02</value>
        </summaryFilterItems>
        <summaryForeignKey>Student_Group__c.SG_Contact__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>CAP__c</fullName>
        <formula>IF(CAP_Student_Group_Count__c &gt; 0, 
IMAGE(&quot;/servlet/servlet.ImageServer?id=015d0000003Poog&amp;oid=&quot;&amp;$Organization.Id,&quot;CAP Participant&quot;,20,20), 
IF(CAP_Ineligible_Student_Group_Count__c &gt; 0, 
IMAGE(&quot;/servlet/servlet.ImageServer?id=015d0000003QCEg&amp;oid=&quot;&amp;$Organization.Id,&quot;CAP Ineligible&quot;,20,20), 
IF(CAP_Possible__c, 
IMAGE(&quot;/servlet/servlet.ImageServer?id=015d0000003Q7J2&amp;oid=&quot;&amp;$Organization.Id,&quot;CAP Possible&quot;,20,20), 
&quot;&quot;)))</formula>
        <inlineHelpText>Displays a green icon for a College Achievement Plan participant. Automatically set when the Contact has one or more Student Group records where Status is True and PeopleSoft Code is CP00, CP01, or CP02.</inlineHelpText>
        <label>CAP</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EMPLID__c</fullName>
        <description>PeopleSoft unique ID</description>
        <externalId>true</externalId>
        <label>EMPLID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

ASUSFETest/src/classes/ContactInfo.cls
global with sharing class ContactInfo {

    public ContactInfo(TestController controller) {

    }


    public ContactInfo(ApexPages.StandardController controller) {
 
    }

    // public User contId {get;set;}
    public Id contId = [SELECT ContactId FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1].ContactId;


    public List<Contact> getContact() {
        return [SELECT Id, Name, EmplId__c, CAP__c, CAP_Student_Group_Count__c FROM Contact WHERE Id = :contId];
    }
    
    public Contact getName() {
        return [SELECT FirstName FROM Contact WHERE Id = :contId];
    }

}